<page>
<div id="contenido">
    <div id="cuerpo">
            <table class="general" summary="Datos" style="font-size: 18px !important;">
                <tr class="color2">
                    <td>{socioLabel}</td>
                    <td>{placaLabel}</td>
                    <td>{marcaMotorLabel}</td>
                    <td>{tipoMotorLabel}</td>
                </tr>
                <tr>
                    <td>{socio}</td>
                    <td>{placa}</td>
                    <td>{marcaMotor}</td>
                    <td>{tipoMotor}</td>
                </tr>
            </table>

             <table class="general" summary="Presentación">

                 <tr class="color1">
                     <td>
                         <p style="font-size: 15px !important;"><strong>LA FLOTA®</strong> agradece su presencia dentro de nuestro programa de mantenimiento y productividad y la confianza depositada para atender su vehículo. Esta comunidad permite ofrecerle a nuestros afiliados servicios y beneficios que garanticen mayor rendimiento y rentabilidad para usted, su conductor y su vehículo, a través de un completo programa de mantenimiento preventivo.</p>
                         <p style="font-size: 15px !important;">Nos permitimos presentar a continuación el resultado de la muestra de Lubricante de su Motor, Los niveles de desgaste que se presentan en el informe son tendencias con las cuales se pueden prevenir fallas mayores y hacen parte del mantenimiento predictivo del motor</p>
                         <br/><br/>
                         <img src="images/flota_1.jpg" alt="la flota" class="imagen_centro" width="700px" />
                         <br/><br/>
                         <p style="font-size: 15px !important;"><strong>Nota importante:</strong> Los niveles de desgaste que se presentan en el informe son tendencias con las cuales se pueden prevenir fallas mayores y hacen parte del mantenimiento predictivo del motor, sin embargo se recomienda ejecutar un programa de mantenimiento preventivo de acuerdo a los siguientes lineamientos*:</p>
                         <p style="font-size: 15px !important;">* Para mayor información y tipos de rutinas, favor remitirse al Manual de Usuario de Motores Cummins.<br />
                            ** En el mantenimiento de cambio de aceite se reemplaza el filtro separador de combustible, el filtro primario se recomienda cambiarlo cada dos cambios y el filtro de aire se reemplaza de acuerdo al indicador de restricción y al análisis del aceite.<br />
                            *** Para el caso de motores serie B, serie C, ISB e ISC, se realiza una verificación del sistema de inyección que puede derivar en la intervención sobre la bomba o los inyectores por desgaste debido a la calidad del combustible, esta intervención no se incluye dentro del valor de la verificación.<br />
                         </p>
                        <p style="font-size: 15px !important;">En motores automotrices se recomienda realizar el primer cambio de aceite a las 150 horas o 4.000 km y basados en los análisis de aceite ir subiendo los intervalos de cambio.</p>
                        <p style="font-size: 15px !important;">Con las verificaciones y calibraciones de sistema de inyección, freno de motor y trenes de válvulas se logra mejorar el ajuste y tolerancia de los componentes del motor, alcanzando un desempeño similar al motor nuevo.</p>
                     </td>
                 </tr>
             </table>
             <div class="saltopagina"></div>
            <table class="encabezado" summary="Encabezado de la impresión">
              <tr>
                    <td colspan="3">
                        <img src="images/logoFlota.png" alt="la flota" width="382" height="78" />
                                    </td>
                    <td style="color: red" class="imprimir" >
                    </td>
              </tr>
            </table>
                       <table class="general" summary="Datos">
                            <tr>
                                <td width="50%">
                                    <div class="cabezoteTrImprimir divCabezote">
                                        Hierro: material metálico que por la estructura del motor se encuentra en varias piezas del mismo.
                                    </div>
                                    <img src="graficar.php?idPlaca=258&campomin=vminfe&campomax=vmaxfe&campomue=fe" class="imagen_centro" width="360px" />
                                    <table class="tablaGraficaImprimir graficaPequeña">
                                        <tr class="cabezoteTrImprimir">
                                            <td></td>
                                                                                             </tr>
                                        <tr>
                                            <td class="cabezoteTrImprimir">Valor Minimo</td>
                                                                                            </tr>
                                        <tr>
                                            <td class="cabezoteTrImprimir">Valor Muestra</td>
                                                                                            </tr>
                                        <tr>
                                            <td class="cabezoteTrImprimir">Valor Maximo</td>
                                                                                            </tr>
                                    </table>    
                                </td>
                                <td width="50%"> 
                                    <div class="cabezoteTrImprimir divCabezote">    
                                    Plomo o Babit: es el primer material metálico que recubre los casquetes.    
                                    </div>
                                    <img src="graficar.php?idPlaca=258&campomin=vminpb&campomax=vmaxpb&campomue=pb" class="imagen_centro" width="360px"/>
                                    <table class="tablaGraficaImprimir graficaPequeña">
                                        <tr class="cabezoteTrImprimir">
                                            <td></td>
                                                                                             </tr>
                                        <tr>
                                            <td class="cabezoteTrImprimir">Valor Minimo</td>
                                                                                            </tr>
                                        <tr>
                                            <td class="cabezoteTrImprimir">Valor Muestra</td>
                                                                                            </tr>
                                        <tr>
                                            <td class="cabezoteTrImprimir">Valor Maximo</td>
                                                                                            </tr>
                                    </table>    
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="cabezoteTrImprimir divCabezote">
                                    Cobre: es el segundo manto metálico que recubre los casquetes.    
                                    </div>    
                                    <img src="graficar.php?idPlaca=258&campomin=vmincu&campomax=vmaxcu&campomue=cu" class="imagen_centro" width="360px"/>
                                    <table class="tablaGraficaImprimir graficaPequeña">
                                    <tr>
                                      <td><table class="tablaGraficaImprimir graficaPequeña">
                                        <tr class="cabezoteTrImprimir">
                                          <td></td>
                                                                                          </tr>
                                        <tr>
                                          <td class="cabezoteTrImprimir">Valor Minimo</td>
                                                                                          </tr>
                                        <tr>
                                          <td class="cabezoteTrImprimir">Valor Muestra</td>
                                                                                          </tr>
                                        <tr>
                                          <td class="cabezoteTrImprimir">Valor Maximo</td>
                                                                                          </tr>
                                      </table></td>
                                    </tr>
                                </table></td>
                                <td>
                                    <div class="cabezoteTrImprimir divCabezote">
                                    Cromo: material metálico que recubre los anillos.
                                    </div>
                                    <img src="graficar.php?idPlaca=258&campomin=vmincr&campomax=vmaxcr&campomue=cr" class="imagen_centro" width="360px"/>
                                    <table class="tablaGraficaImprimir graficaPequeña">
                                        <tr class="cabezoteTrImprimir">
                                            <td></td>
                                                                                            </tr>
                                        <tr>
                                            <td class="cabezoteTrImprimir">Valor Minimo</td>
                                                                                            </tr>
                                        <tr>
                                            <td class="cabezoteTrImprimir">Valor Muestra</td>
                                                                                            </tr>
                                        <tr>
                                            <td class="cabezoteTrImprimir">Valor Maximo</td>
                                                                                            </tr>
                                    </table>
                        </td>
                    </tr>
           </table>
           <div class="saltopagina"></div>
           <table class="general" summary="Datos">
                            <tr>
                                <td width="50%">
                                    <div class="cabezoteTrImprimir divCabezote">
                                    Aluminio: es un material metálico que conforma la estructura de los pistones.
                                    </div>   
                                    <br /><br /><br /><br />                                         
                                    <img src="graficar.php?idPlaca=258&campomin=vminal&campomax=vmaxal&campomue=al" class="imagen_centro" width="360px"/>
                                    <table class="tablaGraficaImprimir graficaPequeña">
                                        <tr class="cabezoteTrImprimir">
                                            <td></td>
                                                                                             </tr>
                                        <tr>
                                            <td class="cabezoteTrImprimir">Valor Minimo</td>
                                                                                            </tr>
                                        <tr>
                                            <td class="cabezoteTrImprimir">Valor Muestra</td>
                                                                                            </tr>
                                        <tr>
                                            <td class="cabezoteTrImprimir">Valor Maximo</td>
                                                                                            </tr>
                                    </table>    
                                </td>
                                <td>
                                    <div class="cabezoteTrImprimir divCabezote">
                                    Silicio: material presente en el medio ambiente y nos determina el estado del sistema de adminsión.
                                    </div>
                                    <br /><br /><br /><br />
                                    <img src="graficar.php?idPlaca=258&campomin=vminsi&campomax=vmaxsi&campomue=si" class="imagen_centro" width="360px"/>
                                    <table class="tablaGraficaImprimir graficaPequeña">
                                        <tr class="cabezoteTrImprimir">
                                            <td></td>
                                                                                           </tr>
                                        <tr>
                                            <td class="cabezoteTrImprimir">Valor Minimo</td>
                                                                                            </tr>
                                        <tr>
                                            <td class="cabezoteTrImprimir">Valor Muestra</td>
                                                                                            </tr>
                                        <tr>
                                            <td class="cabezoteTrImprimir">Valor Maximo</td>
                                                                                            </tr>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="cabezoteTrImprimir divCabezote">
                                    La viscocidad y los demas analisis nos permite establecer posibles prolongaciones de la vida útil del aceite
                                    </div>
                                    <br /><br /><br /><br />
                                    <img src="graficar.php?idPlaca=258&campomin=vminvis&campomax=vmaxvis&campomue=vis100" class="imagen_centro" width="360px"/>
                                    <table class="tablaGraficaImprimir graficaPequeña">
                                        <tr class="cabezoteTrImprimir">
                                            <td></td>
                                                                                             </tr>
                                        <tr>
                                            <td class="cabezoteTrImprimir">Valor Minimo</td>
                                                                                            </tr>
                                        <tr>
                                            <td class="cabezoteTrImprimir">Valor Muestra</td>

                                                                                            </tr>
                                        <tr>
                                            <td class="cabezoteTrImprimir">Valor Maximo</td>
                                                                                            </tr>
                                    </table>
                                </td>
                                <td>
                                    <div class="cabezoteTrImprimir divCabezote">
                                    Hollin
                                    </div> 
                                    <br /><br />  <br /><br />                                        
                                    <img class="imagen_centro" src="graficar.php?idPlaca=258&campomin=vminhollin&campomax=vmaxhollin&campomue=hollin" width="360px" />
                                    <table class="tablaGraficaImprimir graficaPequeña">
                                        <tr class="cabezoteTrImprimir">
                                            <td></td>
                                                                                            </tr>
                                        <tr>
                                            <td class="cabezoteTrImprimir">Valor Minimo</td>
                                                                                            </tr>
                                        <tr>
                                            <td class="cabezoteTrImprimir">Valor Muestra</td>

                                                                                            </tr>
                                        <tr>
                                            <td class="cabezoteTrImprimir">Valor Maximo</td>
                                                                                            </tr>
                                    </table>                                            

                            </tr>                                    
                        </table>
                                        <div class="saltopagina"></div>
                <table class="general" style="margin: 1px auto">
                <tr class="color2" style="font-size: 18px">
                    <td>Otras variables</td>
                </tr>
                <tr>
                    <td>
                        <table style="width: 100%">
                            <tr class="color2">
                                <td>Fecha</td>
                                <td>Combustible</td>
                                <td>Agua</td>
                                <td>TBN</td>
                            </tr>
                                                            </table>     


                    </td>
                </tr>                            
                </table>
                <br /><br /><br /><br />
                <table class="tablaGraficaImprimir" style="margin: 1px auto">
                 <tr>
                     <td>
                         <p>Conforme a las graficas obtenidas se presentan a continuación las siguientes recomendaciones para cada uno de los vehículos:</p>
                     </td>
                 </tr>
                </table>
                <table class="general" summary="Datos">
                <tr class="color2">
                       <td style="font-size: 15px; text-align: center; font-weight: bold; ">Aceite De Motor</td>
                </tr>
                <tr>
                    <td>
                       <table class="general" summary="Datos">
                <tr class="color2">
                                <td>Ultima Fecha De Cambio</td>
                                <td>Placa</td>
                                <td>Kilometraje</td>
                                <td>Periodo de Cambio (km)</td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>FCE274</td>
                                <td></td>
                                <td>0</td>
                            </tr>
                        </table>     


                    </td>
                </tr>    
               <tr class="color2">
                    <td style="font-size: 15px; text-align: center; font-weight: bold; ">Observaciones del comite tecnico de la flota</td>
                </tr>
                <tr>
                    <td align="center">
                         <table class="general" summary="Datos">
                <tr class="color2">
                                <td>Item</td>
                                <td>Observaciones</td>
                                <td>Fecha</td>
                            </tr>

                                                            </table>

                    </td>
                </tr>
                </table>

               <table class="general" summary="Datos">
                <tr class="color2">
                    <td style="font-size: 15px; text-align: center; font-weight: bold; ">Número de muestra y kilometros en la toma</td>
                </tr>
                <tr>
                    <td align="center">
                         <table class="general" summary="Datos">
                <tr class="color2">
                                <td>Item</td>
                                <td>N° Muestra</td>
                                <td>Kilometros</td>
                            </tr>

                        </table>

                    </td>
                </tr>
            </table>

          <table class="general" summary="Presentación">

                 <tr class="color1">
                     <td>
                         <p>Posibles causas de aumento de tierra dentro del motor son:<br />
<ol>
<li> Soplado de filtro de aire, lo que ocasiona daños irreversibles en el componente filtrante aumentado de tamaño los poros.</li>
<li> Retirar y poner los filtros de aire ya que se generan entradas de tierra.</li>
<li> El estado del sistema de admisión (hermeticidad), ya que pueden existir componentes flojos o sueltos por los cuales se genere entrada de tierra al motor.</li>
</ol>
</p>
 <p> Posibles causas de aumento en la viscosidad del aceite son:
    <ol>
        <li> Excesivo sedimento dentro del carter.</li>
        <li> Contaminación con refrigerante, lo que provoca oxidación y degradación del aceite.</li>
        <li> Entrada de gases de combustión al carter por excesivos tiempos en mínima.</li>
        <li> Hollín por mala combustión dentro de las cámaras del motor.</li>
        <li> Periodos de cambio muy extendido lo cual causa una excesiva degradación del aceite.</li>
    </ol>
</p>

<p> De acuerdo al comportamiento y las tendencias de las muestras de aceite en cuanto a desgaste y viscosidad a lo largo de tres mantenimientos y al consumo de aceite, se harán extensiones en los periodos de cambio, aumentando la productividad de su(s) vehículo(s).</p>
<p>Cualquier duda o comentario adicional respecto al informe no dude en comunicarla, Cordialmente,</p>

<img src="images/firmaBernal.png" alt="la flota" width="100px" />
<p>
    Ing. Edgar Eduardo Bernal<br />
    JEFE DE MANTENIMIENTO FLOTA<br />
    Tel. 3118267402<br />
</p>

                     </td>
                 </tr>
        </table>
                   </div>
    <div style="clear: both"></div>
</div>
</page>    