<page>
    <div class="header fullWidth">{slogan}</div>

    <table cellspacing="0" align="center">
        <tr>
            <th class="borderLeft width300">{socioLabel}</th>
            <th class="width50">{placaLabel}</th>
            <th class="width150">{marcaMotorLabel}</th>
            <th class="width100">{tipoMotorLabel}</th>
        </tr>
        <tr>
            <td class="borderLeft">{socio}</td>
            <td>{placa}</td>
            <td>{marcaMotor}</td>
            <td>{tipoMotor}</td>
        </tr>
    </table>

    <table cellspacing="0" align="center">
        <tr>
            <td class="borderLeft fullWidth">
                <p>
                    <strong>LA FLOTA®</strong> agradece su presencia dentro de nuestro programa de mantenimiento y productividad y la confianza depositada para atender su vehículo. Esta comunidad permite ofrecerle a nuestros afiliados servicios y beneficios que garanticen mayor rendimiento y rentabilidad para usted, su conductor y su vehículo, a través de un completo programa de mantenimiento preventivo.
                </p>
                <p>
                    A continuación presentamos el resultado de la muestra de lubricante de su motor. Los niveles de desgaste que se presentan en el informe son tendencias con las cuales se pueden prevenir fallas mayores y hacen parte del mantenimiento predictivo del motor.
                </p>
            </td>
        </tr>
    </table>

    <table cellspacing="8" align="center" class="noBorder">
        <tr>
            <td class="width320 borderLeft">
                <table cellspacing="0" align="center" class="noBorder">
                    <tr>
                        <td class="noBorder width320"><p>{feLegend}</p></td>
                    </tr>
                    <tr>
                        <td class="noBorder width320">{feChart}</td>
                    </tr>
                    <tr>
                        <td class="noBorder width320">{feTable}</td>
                    </tr>
                </table>
            </td>
            <td class="width320 borderLeft">
                <table cellspacing="0" align="center" class="noBorder">
                    <tr>
                        <td class="noBorder width320"><p>{pbLegend}</p></td>
                    </tr>
                    <tr>
                        <td class="noBorder width320">{pbChart}</td>
                    </tr>
                    <tr>
                        <td class="noBorder width320">{pbTable}</td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <table cellspacing="8" align="center" class="noBorder">
        <tr>
            <td class="width320 borderLeft">
                <table cellspacing="0" align="center" class="noBorder">
                    <tr>
                        <td class="noBorder width320"><p>{cuLegend}</p></td>
                    </tr>
                    <tr>
                        <td class="noBorder width320">{cuChart}</td>
                    </tr>
                    <tr>
                        <td class="noBorder width320">{cuTable}</td>
                    </tr>
                </table>
            </td>
            <td class="width320 borderLeft">
                <table cellspacing="0" align="center" class="noBorder">
                    <tr>
                        <td class="noBorder width320"><p>{crLegend}</p></td>
                    </tr>
                    <tr>
                        <td class="noBorder width320">{crChart}</td>
                    </tr>
                    <tr>
                        <td class="noBorder width320">{crTable}</td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</page>
<page>
    <div class="header fullWidth">{slogan}</div>
    <table cellspacing="8" align="center" class="noBorder">
        <tr>
            <td class="width320 borderLeft">
                <table cellspacing="0" align="center" class="noBorder">
                    <tr>
                        <td class="noBorder width320"><p>{alLegend}</p></td>
                    </tr>
                    <tr>
                        <td class="noBorder width320">{alChart}</td>
                    </tr>
                    <tr>
                        <td class="noBorder width320">{alTable}</td>
                    </tr>
                </table>
            </td>
            <td class="width320 borderLeft">
                <table cellspacing="0" align="center" class="noBorder">
                    <tr>
                        <td class="noBorder width320"><p>{siLegend}</p></td>
                    </tr>
                    <tr>
                        <td class="noBorder width320">{siChart}</td>
                    </tr>
                    <tr>
                        <td class="noBorder width320">{siTable}</td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <table cellspacing="8" align="center" class="noBorder">
        <tr>
            <td class="width320 borderLeft">
                <table cellspacing="0" align="center" class="noBorder">
                    <tr>
                        <td class="noBorder width320"><p>{vis100Legend}</p></td>
                    </tr>
                    <tr>
                        <td class="noBorder width320">{vis100Chart}</td>
                    </tr>
                    <tr>
                        <td class="noBorder width320">{vis100Table}</td>
                    </tr>
                </table>
            </td>
            <td class="width320 borderLeft">
                <table cellspacing="0" align="center" class="noBorder">
                    <tr>
                        <td class="noBorder width320" align="center"><p>{hollinLegend}</p></td>
                    </tr>
                    <tr>
                        <td class="noBorder width320">{hollinChart}</td>
                    </tr>
                    <tr>
                        <td class="noBorder width320">{hollinTable}</td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <table cellspacing="0" align="center">
        <tr>
            <th class="borderLeft fullWidth">
                Otras variables
            </th>
        </tr>
    </table>
    <table cellspacing="0" align="center">
        <tr>
            <th class="borderLeft width150">{fechaLabel}</th>
            <th class="width150">{combustibleLabel}</th>
            <th class="width150">{aguaLabel}</th>
            <th class="width150">{tbnLabel}</th>
        </tr>
        {otrasVariablesRows}
    </table>
</page>
<page>
    <div class="header fullWidth">{slogan}</div>
    <div class="fullWidth">
        A continuación relacionamos las recomendaciones del grupo de ingeniería:
    </div>
    <table cellspacing="0" align="center">
        <tr>
            <th class="borderLeft fullWidth">
                Aceite de {tipo}
            </th>
        </tr>
    </table>
    <table cellspacing="0" align="center">
        <tr>
            <th class="borderLeft width30">{itemLabel}</th>
            <th class="width523">{observacionesLabel}</th>
            <th class="width70">{fechaLabel}</th>
        </tr>
        {tipoAceiteRows}
    </table>
    <br>
    <table cellspacing="0" align="center">
        <tr>
            <th class="borderLeft fullWidth">
                Número de muestra y kilómetros
            </th>
        </tr>
    </table>
    <table cellspacing="0" align="center">
        <tr>
            <th class="borderLeft width223">{itemLabel}</th>
            <th class="width223">{muestraLabel}</th>
            <th class="width223">{kilometrosLabel}</th>
        </tr>
        {infoMuestrasRows}
    </table>
</page>
<page>
    <div class="fullWidth">
        <ul>
            <li><p>Si el resultado de su muestra es <strong>CRÍTICO</strong>, comuníquese con su asesor o con el grupo de productividad (Tel. 2948444 ext. 4507 Cel. 314-4116975), para ampliar la información y hacer las respectivas recomendaciones.</p></li>
            <li><p>Si el resultado de su muestra es <strong>PRECAUCIÓN</strong>, le informamos que su vehículo entro en seguimiento por parte de La Flota, Recuerde que este resultado no inhabilita la operación del vehículo, no obstante verifique el cumplimiento de las recomendaciones establecidas en el manual de usuario de su motor</p></li>
            <li><p>Si el resultado de su muestra es <strong>NORMAL</strong>, por favor seguir con las prácticas adecuadas de mantenimiento especificadas en el manual de usuario de su motor.</p></li>
        </ul>
    </div>
    <table cellspacing="0" align="center">
        <tr>
            <th class="borderLeft fullWidth">
                COMPONENTES DE MOTOR
            </th>
        </tr>
        <tr>
            <td class="borderLeft fullWidth">
                <p>
                Para su mayor entendimiento, a continuación relacionamos una tabla en donde podrá observar los elementos que componen las partes de su motor.
                </p>
                <img style="margin: 10px 0 0 60px;" src="{tablaComponentes}">
                <p>Para mayor información y tipos de rutinas, favor remitirse al manual de usuario de su motor</p>
            </td>
        </tr>
    </table>
</page>