<page>
    <div class="header fullWidth">{slogan}</div>
    <div>
        <table cellspacing="0" align="center">
            <tr>
                <th class="borderLeft width300">{socioLabel}</th>
                <th class="width50">{placaLabel}</th>
                <th class="width150">{marcaMotorLabel}</th>
                <th class="width100">{tipoMotorLabel}</th>
            </tr>
            <tr>
                <td class="borderLeft">{socio}</td>
                <td>{placa}</td>
                <td>{marcaMotor}</td>
                <td>{tipoMotor}</td>
            </tr>
        </table>
        
        <table cellspacing="0" align="center">
            <tr>
                <td class="borderLeft fullWidth">
                    <p>
                        <strong>LA FLOTA®</strong> agradece su presencia dentro de nuestro programa de mantenimiento y productividad y la confianza depositada para atender su vehículo. Esta comunidad permite ofrecerle a nuestros afiliados servicios y beneficios que garanticen mayor rendimiento y rentabilidad para usted, su conductor y su vehículo, a través de un completo programa de mantenimiento preventivo.
                    </p>
                    <p>
                        Nos permitimos presentar a continuación el resultado de la muestra de Lubricante de su Motor, Los niveles de desgaste que se presentan en el informe son tendencias con las que se pueden prevenir fallas mayores y hacen parte del mantenimiento predictivo del motor.
                    </p>
                </td>
            </tr>
        </table>
    </div>
    <div id="charts"></div>
</page>
<page>
    <div class="header fullWidth">{slogan}</div>
    <table cellspacing="0" align="center">
        <tr>
            <th class="borderLeft fullWidth">
                Otras variables
            </th>
        </tr>
    </table>
    <table cellspacing="0" align="center">
        <tr>
            <th class="borderLeft width150">{fechaLabel}</th>
            <th class="width150">{combustibleLabel}</th>
            <th class="width150">{aguaLabel}</th>
            <th class="width150">{tbnLabel}</th>
        </tr>
        {otrasVariablesRows}
    </table>
    <div class="fullWidth">
        A continuación relacionamos las recomendaciones del grupo de ingeniería:
    </div>
    <table cellspacing="0" align="center">
        <tr>
            <th class="borderLeft fullWidth">
                Aceite de {tipo}
            </th>
        </tr>
    </table>
    <table cellspacing="0" align="center">
        <tr>
            <th class="borderLeft width30">{itemLabel}</th>
            <th class="width523">{observacionesLabel}</th>
            <th class="width70">{fechaLabel}</th>
        </tr>
        {tipoAceiteRows}
    </table>
    <br>
    <table cellspacing="0" align="center">
        <tr>
            <th class="borderLeft fullWidth">
                Número de muestra y kilómetros
            </th>
        </tr>
    </table>
    <table cellspacing="0" align="center">
        <tr>
            <th class="borderLeft width223">{itemLabel}</th>
            <th class="width223">{muestraLabel}</th>
            <th class="width223">{kilometrosLabel}</th>
        </tr>
        {infoMuestrasRows}
    </table>
    <div class="fullWidth">
        <ul>
            <li>Si el resultado de Su muestra es CRÍTICO, comuníquese con su asesor o con el grupo de productividad (Tel. 2948444 ext. 4507 Cel. 314-4116975), para ampliar la información y hacer las respectivas recomendaciones.</li>
            <li>Si el resultado de su muestra es PRECAUCIÓN, le informamos que su vehículo entro en seguimiento por parte de La Flota, Recuerde que este resultado no inhabilita la operación del vehículo, no obstante verifique el cumplimiento de las recomendaciones establecidas en el manual de usuario de su motor</li>
            <li>Si el Resultadio de su muestra es NORMAL, por favor seguir con las practicas adecuadas de mantenimiento especificadas en el manual de usuario de su motor.</li>
        </ul>
    </div>
    <table cellspacing="0" align="center">
        <tr>
            <th class="borderLeft fullWidth">
                COMPONENTES DE MOTOR
            </th>
        </tr>
        <tr>
            <td class="borderLeft">
                Para su mayor entendimiento, a continuación relacionamos una tabla en donde podrá observar los elementos que componen las partes de su motor.
            </td>
        </tr>
    </table>
    
</page>